/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Backend.Gestion_Administrativos;
import Backend.Gestion_cliente;
import Conexion.conexion_bd;
import Frontend.Dashboard;
import Objects.cls_cliente;
import Frontend.frmLogin;
import Objects.cls_administrativos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JOptionPane;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDarkerIJTheme;

/**
 *
 * @author juanse
 */
public class PN_clientes extends javax.swing.JPanel {

    conexion_bd Conn;
    String usuario;
    String con;

    public PN_clientes() {
        initComponents();
        Conn = new conexion_bd();
        Conn.establecer();
        Errores();
        LimpiarCampos();
        LlenarTabla();
        usuario = "";
        con = "";

    }

    public void Errores() {
        lbl_error_IDcliente.setVisible(false);
        lbl_error_TipoIDcliente.setVisible(false);
        lbl_error_Documentocliente.setVisible(false);
        lbl_error_Nombrecliente.setVisible(false);
        lbl_error_Apellidocliente.setVisible(false);
        lbl_error_edad.setVisible(false);
        lbl_error_movil.setVisible(false);
        lbl_error_genero.setVisible(false);
        lbl_error_direccion.setVisible(false);
    }

    public void LimpiarCampos() {
        txt_id.setText("");
        cbx_tipo_doc.setSelectedIndex(0);
        txt_Num_doc.setText("");
        txt_nombres.setText("");
        txt_apellidos.setText("");
        txt_edad.setText("");
        txt_movil.setText("");
        cbx_genero.setSelectedIndex(0);
        txt_direccion.setText("");
    }

    public void LlenarTabla() {
        Gestion_cliente objCli = new Gestion_cliente();
        tbl_cli.setModel(objCli.ListarClientes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_clientes = new javax.swing.JPanel();
        PN_data = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_tipoDoc = new javax.swing.JLabel();
        cbx_tipo_doc = new javax.swing.JComboBox<>();
        lbl_error_IDcliente = new javax.swing.JLabel();
        lbl_error_TipoIDcliente = new javax.swing.JLabel();
        lbl_numDoc = new javax.swing.JLabel();
        txt_Num_doc = new javax.swing.JTextField();
        lbl_error_Documentocliente = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        lbl_error_Nombrecliente = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        lbl_error_Apellidocliente = new javax.swing.JLabel();
        lbl_edad = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        lbl_error_genero = new javax.swing.JLabel();
        lbl_movil = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_genero = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        cbx_genero = new javax.swing.JComboBox<>();
        txt_movil = new javax.swing.JTextField();
        lbl_error_edad = new javax.swing.JLabel();
        lbl_error_direccion = new javax.swing.JLabel();
        lbl_error_movil = new javax.swing.JLabel();
        btn_mostrar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_crear = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        PN_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cli = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(750, 390));

        PN_clientes.setBackground(new java.awt.Color(0, 0, 0));
        PN_clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PN_data.setBackground(new java.awt.Color(0, 0, 0));
        PN_data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID:");
        lbl_id.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        PN_data.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 30));

        lbl_tipoDoc.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        lbl_tipoDoc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipoDoc.setText("Tipo de documento:");
        lbl_tipoDoc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_tipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        cbx_tipo_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el documento", "Cedula de Ciudadania", "Cedula de extranjeria", "Tarjeta de identidad", "Otro" }));
        cbx_tipo_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tipo_docActionPerformed(evt);
            }
        });
        PN_data.add(cbx_tipo_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 160, 30));

        lbl_error_IDcliente.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_IDcliente.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_IDcliente.setForeground(new java.awt.Color(187, 2, 2));
        lbl_error_IDcliente.setText("*Error,debe ingresar el ID del cliente");
        PN_data.add(lbl_error_IDcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 10));

        lbl_error_TipoIDcliente.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_TipoIDcliente.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_TipoIDcliente.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_TipoIDcliente.setText("*Error,debe ingresar el tipo de ID del cliente");
        PN_data.add(lbl_error_TipoIDcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 10));

        lbl_numDoc.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_numDoc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_numDoc.setText("Num Documento:");
        lbl_numDoc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_numDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        txt_Num_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Num_docActionPerformed(evt);
            }
        });
        PN_data.add(txt_Num_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 170, 30));

        lbl_error_Documentocliente.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_Documentocliente.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_Documentocliente.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_Documentocliente.setText("*Error,debe ingresar el Documento del cliente");
        PN_data.add(lbl_error_Documentocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 10));

        lbl_nombres.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setText("Nombres:");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        PN_data.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, 30));

        lbl_error_Nombrecliente.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_Nombrecliente.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_Nombrecliente.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_Nombrecliente.setText("*Error,debe ingresar los Nombres del cliente");
        PN_data.add(lbl_error_Nombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 10));

        lbl_apellidos.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_apellidos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apellidos.setText("Apellidos:");
        lbl_apellidos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, -1));
        PN_data.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 230, 30));

        lbl_error_Apellidocliente.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_Apellidocliente.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_Apellidocliente.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_Apellidocliente.setText("*Error,debe ingresar los Apellidos del cliente");
        PN_data.add(lbl_error_Apellidocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 10));

        lbl_edad.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_edad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_edad.setText("Edad:");
        lbl_edad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        PN_data.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 290, 30));

        lbl_error_genero.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_genero.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_genero.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_genero.setText("*Error,debe ingresar el genero del cliente");
        PN_data.add(lbl_error_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 10));

        lbl_movil.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_movil.setForeground(new java.awt.Color(255, 255, 255));
        lbl_movil.setText("Movil:");
        lbl_movil.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_movil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lbl_direccion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_direccion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_direccion.setText("Dirección:");
        lbl_direccion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        lbl_genero.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_genero.setForeground(new java.awt.Color(255, 255, 255));
        lbl_genero.setText("Genero:");
        lbl_genero.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        PN_data.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 250, 30));

        cbx_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un genero", "Hombre", "Mujer", "No binario", "Otros" }));
        PN_data.add(cbx_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 270, -1));

        txt_movil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_movilActionPerformed(evt);
            }
        });
        PN_data.add(txt_movil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 290, 30));

        lbl_error_edad.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_edad.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_edad.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_edad.setText("*Error,debe ingresar la edad del cliente");
        PN_data.add(lbl_error_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 10));

        lbl_error_direccion.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_direccion.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_direccion.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_direccion.setText("*Error,debe ingresar la direccion del cliente");
        PN_data.add(lbl_error_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, 10));

        lbl_error_movil.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_movil.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_movil.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_movil.setText("*Error,debe ingresar el telefono del cliente");
        PN_data.add(lbl_error_movil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 10));

        btn_mostrar.setBackground(new java.awt.Color(0, 0, 0));
        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clients/hide (1).png"))); // NOI18N
        btn_mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        PN_data.add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 50, 30));

        PN_clientes.add(PN_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 370));

        btn_actualizar.setBackground(new java.awt.Color(0, 0, 0));
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clients/loop (1).png"))); // NOI18N
        btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        PN_clientes.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 50, 30));

        btn_crear.setBackground(new java.awt.Color(0, 0, 0));
        btn_crear.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        btn_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clients/add (1).png"))); // NOI18N
        btn_crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });
        PN_clientes.add(btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 50, 30));

        btn_eliminar.setBackground(new java.awt.Color(0, 0, 0));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clients/bin (1).png"))); // NOI18N
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        PN_clientes.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 50, 30));

        PN_table.setBackground(new java.awt.Color(0, 0, 0));

        tbl_cli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_cli);

        javax.swing.GroupLayout PN_tableLayout = new javax.swing.GroupLayout(PN_table);
        PN_table.setLayout(PN_tableLayout);
        PN_tableLayout.setHorizontalGroup(
            PN_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        PN_tableLayout.setVerticalGroup(
            PN_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_tableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        PN_clientes.add(PN_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 400, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_tipo_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tipo_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tipo_docActionPerformed

    private void txt_Num_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Num_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Num_docActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void txt_movilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_movilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_movilActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed

        Gestion_Administrativos GAdmin = new Gestion_Administrativos();
        cls_administrativos OBJAdmin = new cls_administrativos();

        usuario = OBJAdmin.getUsuario1();
        con = OBJAdmin.getContrasena();
        cls_administrativos tipo_nivel = GAdmin.GuardarDatos(usuario, con);

        System.out.println(tipo_nivel);
        if (tipo_nivel.getTipo_usuario().equals("Administrador")) {
            Gestion_cliente CLI = new Gestion_cliente();
            Errores();
            String ID;
            String Tipo_doc;
            String Num_doc;
            String Nombres;
            String Apellidos;
            String Edad;
            String Movil;
            String Genero;
            String Direccion;

            ID = txt_id.getText();
            Tipo_doc = cbx_tipo_doc.getSelectedItem().toString();
            Num_doc = txt_Num_doc.getText();
            Nombres = txt_nombres.getText();
            Apellidos = txt_apellidos.getText();
            Edad = txt_edad.getText();
            Movil = txt_movil.getText();
            Genero = cbx_genero.getSelectedItem().toString();
            Direccion = txt_direccion.getText();

            if (!ID.equalsIgnoreCase("")) {
                if (!Tipo_doc.equalsIgnoreCase("Seleccione el documento")) {
                    if (!Num_doc.equalsIgnoreCase("")) {
                        if (!Nombres.equalsIgnoreCase("")) {
                            if (!Apellidos.equalsIgnoreCase("")) {
                                if (!Edad.equalsIgnoreCase("")) {
                                    if (!Movil.equalsIgnoreCase("")) {
                                        if (!Genero.equalsIgnoreCase("Selecciona un genero")) {
                                            if (!Direccion.equalsIgnoreCase("")) {
                                                //ACCIONES
                                                Objects.cls_cliente obj_cliente = new Objects.cls_cliente();
                                                obj_cliente.setID_cliente(Long.parseLong(ID));
                                                obj_cliente.setTipo_Documento(Tipo_doc);
                                                obj_cliente.setDocumento(Num_doc);
                                                obj_cliente.setNombres(Nombres);
                                                obj_cliente.setApellidos(Apellidos);
                                                obj_cliente.setEdad(Integer.parseInt(Edad));
                                                obj_cliente.setTelefono(Long.parseLong(Movil));
                                                obj_cliente.setSexo(Genero);
                                                obj_cliente.setDireccion(Direccion);
                                                JOptionPane.showMessageDialog(PN_clientes, CLI.Crear_Cliente(obj_cliente));
                                                LimpiarCampos();
                                                LlenarTabla();
                                            } else {
                                                lbl_error_direccion.setVisible(true);
                                            }
                                        } else {
                                            lbl_error_genero.setVisible(true);
                                        }
                                    } else {
                                        lbl_error_movil.setVisible(true);
                                    }
                                } else {
                                    lbl_error_edad.setVisible(true);
                                }
                            } else {
                                lbl_error_Apellidocliente.setVisible(true);
                            }
                        } else {
                            lbl_error_Nombrecliente.setVisible(true);
                        }
                    } else {
                        lbl_error_Documentocliente.setVisible(true);
                    }
                } else {
                    lbl_error_TipoIDcliente.setVisible(true);

                }
            } else {
                lbl_error_IDcliente.setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(PN_clientes, "No tiene los permisos suficientes");
            LimpiarCampos();
        }


    }//GEN-LAST:event_btn_crearActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed

        String IDCli = txt_id.getText();
        Gestion_cliente GCLiente = new Gestion_cliente();
        cls_cliente objCliente = new cls_cliente();
        Errores();

        if (!IDCli.equalsIgnoreCase(null)) {
            long idcliente = Long.parseLong(IDCli);
            objCliente = GCLiente.BuscarPorID(idcliente);
            
            LimpiarCampos();
            txt_id.setText(String.valueOf(objCliente.getID_cliente()));
            cbx_tipo_doc.setSelectedItem(objCliente.getTipo_Documento());
            txt_Num_doc.setText(objCliente.getDocumento());
            txt_nombres.setText(objCliente.getNombres());
            txt_apellidos.setText(objCliente.getApellidos());
            txt_edad.setText(String.valueOf(objCliente.getEdad()));
            txt_movil.setText(String.valueOf(objCliente.getTelefono()));
            cbx_genero.setSelectedItem(objCliente.getSexo());
            txt_direccion.setText(objCliente.getDireccion());

            JOptionPane.showMessageDialog(null, "Cliente encontrado exitosamente");
            LlenarTabla();

        } else {
            lbl_error_IDcliente.setVisible(true);
        }

    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        Gestion_cliente CLI = new Gestion_cliente();
        Gestion_Administrativos GAdmin = new Gestion_Administrativos();
        cls_administrativos OBJAdmin = new cls_administrativos();

        usuario = OBJAdmin.getUsuario1();
        con = OBJAdmin.getContrasena();
        cls_administrativos tipo_nivel = GAdmin.GuardarDatos(usuario, con);

        if (tipo_nivel.getTipo_usuario().equals("Administrador")) {
            Errores();
            String IDCliente;

            IDCliente = txt_id.getText();
            if (!IDCliente.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(PN_clientes, CLI.Eliminar_cliente(Long.parseLong(IDCliente)));
                LimpiarCampos();
                LlenarTabla();
            } else {
                lbl_error_IDcliente.setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(PN_clientes, "No tiene los permisos suficientes");
            LimpiarCampos();
        }


    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        Gestion_cliente CLI = new Gestion_cliente();
        Gestion_Administrativos GAdmin = new Gestion_Administrativos();
        cls_administrativos OBJAdmin = new cls_administrativos();

        usuario = OBJAdmin.getUsuario1();
        con = OBJAdmin.getContrasena();
        cls_administrativos tipo_nivel = GAdmin.GuardarDatos(usuario, con);

        if (tipo_nivel.getTipo_usuario().equals("Administrador")) {

            Errores();
            String ID;
            String Tipo_doc;
            String Num_doc;
            String Nombres;
            String Apellidos;
            String Edad;
            String Movil;
            String Genero;
            String Direccion;

            ID = txt_id.getText();
            Tipo_doc = cbx_tipo_doc.getSelectedItem().toString();
            Num_doc = txt_Num_doc.getText();
            Nombres = txt_nombres.getText();
            Apellidos = txt_apellidos.getText();
            Edad = txt_edad.getText();
            Movil = txt_movil.getText();
            Genero = cbx_genero.getSelectedItem().toString();
            Direccion = txt_direccion.getText();

            if (!ID.equalsIgnoreCase("")) {
                if (!Tipo_doc.equalsIgnoreCase("Seleccione el documento")) {
                    if (!Num_doc.equalsIgnoreCase("")) {
                        if (!Nombres.equalsIgnoreCase("")) {
                            if (!Apellidos.equalsIgnoreCase("")) {
                                if (!Edad.equalsIgnoreCase("")) {
                                    if (!Movil.equalsIgnoreCase("")) {
                                        if (!Genero.equalsIgnoreCase("Selecciona un genero")) {
                                            if (!Direccion.equalsIgnoreCase("")) {
                                                //ACCIONES
                                                Objects.cls_cliente obj_cliente = new Objects.cls_cliente();
                                                obj_cliente.setID_cliente(Long.parseLong(ID));
                                                obj_cliente.setTipo_Documento(Tipo_doc);
                                                obj_cliente.setDocumento(Num_doc);
                                                obj_cliente.setNombres(Nombres);
                                                obj_cliente.setApellidos(Apellidos);
                                                obj_cliente.setEdad(Integer.parseInt(Edad));
                                                obj_cliente.setTelefono(Long.parseLong(Movil));
                                                obj_cliente.setSexo(Genero);
                                                obj_cliente.setDireccion(Direccion);

                                                JOptionPane.showMessageDialog(PN_clientes, CLI.Actualizar_cliente(obj_cliente, Long.parseLong(ID)));
                                                LimpiarCampos();
                                                LlenarTabla();

                                            } else {
                                                lbl_error_direccion.setVisible(true);
                                            }
                                        } else {
                                            lbl_error_genero.setVisible(true);
                                        }
                                    } else {
                                        lbl_error_movil.setVisible(true);
                                    }
                                } else {
                                    lbl_error_edad.setVisible(true);
                                }
                            } else {
                                lbl_error_Apellidocliente.setVisible(true);
                            }
                        } else {
                            lbl_error_Nombrecliente.setVisible(true);
                        }
                    } else {
                        lbl_error_Documentocliente.setVisible(true);
                    }
                } else {
                    lbl_error_TipoIDcliente.setVisible(true);

                }
            } else {
                lbl_error_IDcliente.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(PN_clientes, "No tiene los permisos suficientes");
            LimpiarCampos();
        }
    }//GEN-LAST:event_btn_actualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PN_clientes;
    private javax.swing.JPanel PN_data;
    private javax.swing.JPanel PN_table;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JComboBox<String> cbx_genero;
    private javax.swing.JComboBox<String> cbx_tipo_doc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_edad;
    private javax.swing.JLabel lbl_error_Apellidocliente;
    private javax.swing.JLabel lbl_error_Documentocliente;
    private javax.swing.JLabel lbl_error_IDcliente;
    private javax.swing.JLabel lbl_error_Nombrecliente;
    private javax.swing.JLabel lbl_error_TipoIDcliente;
    private javax.swing.JLabel lbl_error_direccion;
    private javax.swing.JLabel lbl_error_edad;
    private javax.swing.JLabel lbl_error_genero;
    private javax.swing.JLabel lbl_error_movil;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_movil;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_numDoc;
    private javax.swing.JLabel lbl_tipoDoc;
    private javax.swing.JTable tbl_cli;
    private javax.swing.JTextField txt_Num_doc;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_movil;
    private javax.swing.JTextField txt_nombres;
    // End of variables declaration//GEN-END:variables
}
