/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Backend.GestionProducto;
import Backend.Gestion_Administrativos;
import Conexion.conexion_bd;
import Objects.clsProductos;
import Objects.cls_administrativos;
import javax.swing.JOptionPane;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDarkerIJTheme;
/**
 *
 * @author juanse
 */
public class PN_productos extends javax.swing.JPanel {

    Conexion.conexion_bd Conn;
    String usuario;
    String con;

    public PN_productos() {
        initComponents();
        Conn = new conexion_bd();
        Conn.establecer();
        Errores();
        LlenarTabla();
        usuario = "";
        con = "";
        FlatMaterialDarkerIJTheme.setup();
    }

    public void Errores() {
        lbl_error_IDproducto.setVisible(false);
        lbl_error_NombreProducto.setVisible(false);
        lbl_error_DescripcionProducto.setVisible(false);
        lbl_error_cantidad.setVisible(false);
        lbl_error_categoria.setVisible(false);
        lbl_error_preciodecompra.setVisible(false);
        lbl_error_preciodeventa.setVisible(false);
    }

    public void LimpiarCampos() {
        txt_id_producto.setText("");
        txt_nombre_producto.setText("");
        txt_descripcion_producto.setText("");
        sp_cantidad_prodcuto.setValue(0);
        cbx_categoria_producto.setSelectedIndex(0);
        txt_precio_de_compra.setText("");
        txt_precio_de_venta.setText("");
    }

    public void LlenarTabla() {
        GestionProducto objPRO = new GestionProducto();
        tbl_pro.setModel(objPRO.ListarProductos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_main = new javax.swing.JPanel();
        btn_eliminar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_crear = new javax.swing.JButton();
        PN_data = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        txt_id_producto = new javax.swing.JTextField();
        lbl_error_IDproducto = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre_producto = new javax.swing.JTextField();
        lbl_error_NombreProducto = new javax.swing.JLabel();
        lbl_descri1 = new javax.swing.JLabel();
        txt_descripcion_producto = new javax.swing.JTextField();
        lbl_descri2 = new javax.swing.JLabel();
        lbl_error_DescripcionProducto = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        sp_cantidad_prodcuto = new javax.swing.JSpinner();
        lbl_categoria = new javax.swing.JLabel();
        cbx_categoria_producto = new javax.swing.JComboBox<>();
        lbl_error_cantidad = new javax.swing.JLabel();
        lbl_error_categoria = new javax.swing.JLabel();
        lbl_precio_compra = new javax.swing.JLabel();
        txt_precio_de_compra = new javax.swing.JTextField();
        lbl_error_preciodecompra = new javax.swing.JLabel();
        lbl_error_preciodeventa = new javax.swing.JLabel();
        txt_precio_de_venta = new javax.swing.JTextField();
        lbl_$_precio_compra = new javax.swing.JLabel();
        lbl_$_precio_venta = new javax.swing.JLabel();
        lbl_precio_venta = new javax.swing.JLabel();
        btn_mostrar = new javax.swing.JButton();
        PN_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pro = new javax.swing.JTable();

        PN_main.setBackground(new java.awt.Color(0, 0, 0));
        PN_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_eliminar.setBackground(new java.awt.Color(0, 0, 0));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clients/bin (1).png"))); // NOI18N
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        PN_main.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 50, 30));

        btn_actualizar.setBackground(new java.awt.Color(0, 0, 0));
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clients/loop (1).png"))); // NOI18N
        btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        PN_main.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 50, 30));

        btn_crear.setBackground(new java.awt.Color(0, 0, 0));
        btn_crear.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        btn_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clients/add (1).png"))); // NOI18N
        btn_crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });
        PN_main.add(btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 50, 30));

        PN_data.setBackground(new java.awt.Color(0, 0, 0));
        PN_data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID:");
        lbl_id.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txt_id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_productoActionPerformed(evt);
            }
        });
        PN_data.add(txt_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 270, 30));

        lbl_error_IDproducto.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_IDproducto.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_IDproducto.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_IDproducto.setText("*Error,debe ingresar el ID del producto");
        PN_data.add(lbl_error_IDproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 10));

        lbl_nombre.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("Nombre del producto:");
        lbl_nombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 30));

        txt_nombre_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_productoActionPerformed(evt);
            }
        });
        PN_data.add(txt_nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 150, 30));

        lbl_error_NombreProducto.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_NombreProducto.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_NombreProducto.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_NombreProducto.setText("*Error,debe ingresar el nombre del producto");
        PN_data.add(lbl_error_NombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 10));

        lbl_descri1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_descri1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_descri1.setText("Descripción del ");
        lbl_descri1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_descri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 20));

        txt_descripcion_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcion_productoActionPerformed(evt);
            }
        });
        PN_data.add(txt_descripcion_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 220, 30));

        lbl_descri2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_descri2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_descri2.setText("producto:");
        lbl_descri2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_descri2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 20));

        lbl_error_DescripcionProducto.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_DescripcionProducto.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_DescripcionProducto.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_DescripcionProducto.setText("*Error,debe ingresar la descripcion del cliente");
        PN_data.add(lbl_error_DescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 10));

        lbl_cantidad.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_cantidad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cantidad.setText("Cantidad:");
        lbl_cantidad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        PN_data.add(sp_cantidad_prodcuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 60, -1));

        lbl_categoria.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_categoria.setForeground(new java.awt.Color(255, 255, 255));
        lbl_categoria.setText("Categoria:");
        lbl_categoria.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        cbx_categoria_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el item", "Consumibles", "Flores", "Accesorios", "Otros", " " }));
        PN_data.add(cbx_categoria_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 110, -1));

        lbl_error_cantidad.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_cantidad.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_cantidad.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_cantidad.setText("*Error,debe ingresar la cantidad");
        PN_data.add(lbl_error_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 10));

        lbl_error_categoria.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_categoria.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_categoria.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_categoria.setText("*Error,debe ingresar la categoria");
        PN_data.add(lbl_error_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, 10));

        lbl_precio_compra.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_precio_compra.setForeground(new java.awt.Color(255, 255, 255));
        lbl_precio_compra.setText("Precio de compra");
        lbl_precio_compra.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_precio_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        txt_precio_de_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precio_de_compraActionPerformed(evt);
            }
        });
        PN_data.add(txt_precio_de_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 180, 30));

        lbl_error_preciodecompra.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_preciodecompra.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_preciodecompra.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_preciodecompra.setText("*Error,debe ingresar el precio de compra");
        PN_data.add(lbl_error_preciodecompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, 10));

        lbl_error_preciodeventa.setBackground(new java.awt.Color(153, 0, 0));
        lbl_error_preciodeventa.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        lbl_error_preciodeventa.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_preciodeventa.setText("*Error,debe ingresar el precio venta");
        PN_data.add(lbl_error_preciodeventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, 10));

        txt_precio_de_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precio_de_ventaActionPerformed(evt);
            }
        });
        PN_data.add(txt_precio_de_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, 30));

        lbl_$_precio_compra.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_$_precio_compra.setForeground(new java.awt.Color(255, 255, 255));
        lbl_$_precio_compra.setText("$");
        lbl_$_precio_compra.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_$_precio_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, 20));

        lbl_$_precio_venta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_$_precio_venta.setForeground(new java.awt.Color(255, 255, 255));
        lbl_$_precio_venta.setText("$");
        lbl_$_precio_venta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_$_precio_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 10, -1));

        lbl_precio_venta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_precio_venta.setForeground(new java.awt.Color(255, 255, 255));
        lbl_precio_venta.setText("Precio de venta");
        lbl_precio_venta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PN_data.add(lbl_precio_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        btn_mostrar.setBackground(new java.awt.Color(0, 0, 0));
        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clients/hide (1).png"))); // NOI18N
        btn_mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        PN_data.add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 50, 30));

        PN_main.add(PN_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 350));

        PN_table.setBackground(new java.awt.Color(0, 0, 0));

        tbl_pro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Cantidad", "Precio de compra", "Precio de venta", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tbl_pro);

        javax.swing.GroupLayout PN_tableLayout = new javax.swing.GroupLayout(PN_table);
        PN_table.setLayout(PN_tableLayout);
        PN_tableLayout.setHorizontalGroup(
            PN_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        PN_tableLayout.setVerticalGroup(
            PN_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_tableLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        PN_main.add(PN_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 390, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_productoActionPerformed

    private void txt_nombre_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_productoActionPerformed

    private void txt_descripcion_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcion_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcion_productoActionPerformed

    private void txt_precio_de_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precio_de_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precio_de_compraActionPerformed

    private void txt_precio_de_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precio_de_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precio_de_ventaActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        GestionProducto CLI = new GestionProducto();
        Gestion_Administrativos GAdmin = new Gestion_Administrativos();
        cls_administrativos OBJAdmin = new cls_administrativos();

        usuario = OBJAdmin.getUsuario1();
        con = OBJAdmin.getContrasena();
        cls_administrativos tipo_nivel = GAdmin.GuardarDatos(usuario, con);

        if (tipo_nivel.getTipo_usuario().equals("Administrador")) {

            Errores();
            String ID;
            String Nombre;
            String Descripcion;
            String Cantidad;
            String Categoria;
            String Precio_deC;
            String Precio_deV;

            ID = txt_id_producto.getText();
            Nombre = txt_nombre_producto.getText();
            Descripcion = txt_descripcion_producto.getText();
            Cantidad = sp_cantidad_prodcuto.getValue().toString();
            Categoria = cbx_categoria_producto.getSelectedItem().toString();
            Precio_deC = txt_precio_de_compra.getText();
            Precio_deV = txt_precio_de_venta.getText();
            if (!ID.equalsIgnoreCase("")) {
                if (!Nombre.equalsIgnoreCase("")) {
                    if (!Descripcion.equalsIgnoreCase("")) {
                        if (!Cantidad.equalsIgnoreCase("0")) {
                            if (!Categoria.equalsIgnoreCase("Seleccione el item")) {
                                if (!Precio_deC.equalsIgnoreCase("")) {
                                    if (!Precio_deV.equalsIgnoreCase("")) {

                                        //ACCIONES
                                        Objects.clsProductos objProductos = new Objects.clsProductos();
                                        objProductos.setIDProd(Integer.parseInt(ID));
                                        objProductos.setNombreProd(Nombre);
                                        objProductos.setDescripProd(Descripcion);
                                        objProductos.setCantidadProd(Integer.parseInt(Cantidad));
                                        objProductos.setCategoriaProd(Categoria);
                                        objProductos.setPrecioCompra(Double.parseDouble(Precio_deC));
                                        objProductos.setPrecioVenta(Double.parseDouble(Precio_deV));

                                        JOptionPane.showMessageDialog(null, CLI.AgregarProd(objProductos));
                                        LimpiarCampos();
                                        LlenarTabla();
                                    } else {
                                        lbl_error_preciodeventa.setVisible(true);
                                    }
                                } else {
                                    lbl_error_preciodecompra.setVisible(true);
                                }
                            } else {
                                lbl_error_categoria.setVisible(true);

                            }
                        } else {
                            lbl_error_cantidad.setVisible(true);
                        }
                    } else {
                        lbl_error_DescripcionProducto.setVisible(true);
                    }
                } else {
                    lbl_error_NombreProducto.setVisible(true);
                }
            } else {
                lbl_error_IDproducto.setVisible(true);

            }
        } else {
            JOptionPane.showMessageDialog(null, "No tiene los permisos suficientes");
            LimpiarCampos();
        }
    }//GEN-LAST:event_btn_crearActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        GestionProducto CLI = new GestionProducto();
        Gestion_Administrativos GAdmin = new Gestion_Administrativos();
        cls_administrativos OBJAdmin = new cls_administrativos();

        usuario = OBJAdmin.getUsuario1();
        con = OBJAdmin.getContrasena();
        cls_administrativos tipo_nivel = GAdmin.GuardarDatos(usuario, con);

        System.out.println(tipo_nivel);
        if (tipo_nivel.getTipo_usuario().equals("Administrador")) {

            Errores();
            String ID;
            String Nombre;
            String Descripcion;
            String Cantidad;
            String Categoria;
            String Precio_deC;
            String Precio_deV;

            ID = txt_id_producto.getText();
            Nombre = txt_nombre_producto.getText();
            Descripcion = txt_descripcion_producto.getText();
            Cantidad = sp_cantidad_prodcuto.getValue().toString();
            Categoria = cbx_categoria_producto.getSelectedItem().toString();
            Precio_deC = txt_precio_de_compra.getText();
            Precio_deV = txt_precio_de_venta.getText();
            if (!ID.equalsIgnoreCase("")) {
                if (!Nombre.equalsIgnoreCase("")) {
                    if (!Descripcion.equalsIgnoreCase("")) {
                        if (!Cantidad.equalsIgnoreCase("0")) {
                            if (!Categoria.equalsIgnoreCase("Seleccione el item")) {
                                if (!Precio_deC.equalsIgnoreCase("")) {
                                    if (!Precio_deV.equalsIgnoreCase("")) {

                                        //ACCIONES
                                        Objects.clsProductos objProductos = new Objects.clsProductos();
                                        objProductos.setIDProd(Integer.parseInt(ID));
                                        objProductos.setNombreProd(Nombre);
                                        objProductos.setDescripProd(Descripcion);
                                        objProductos.setCantidadProd(Integer.parseInt(Cantidad));
                                        objProductos.setCategoriaProd(Categoria);
                                        objProductos.setPrecioCompra(Double.parseDouble(Precio_deC));
                                        objProductos.setPrecioVenta(Double.parseDouble(Precio_deV));

                                        JOptionPane.showMessageDialog(null, CLI.EliminarProducto(Long.parseLong(ID)));
                                        LimpiarCampos();
                                        LlenarTabla();
                                    } else {
                                        lbl_error_preciodeventa.setVisible(true);
                                    }
                                } else {
                                    lbl_error_preciodecompra.setVisible(true);
                                }
                            } else {
                                lbl_error_categoria.setVisible(true);

                            }
                        } else {
                            lbl_error_cantidad.setVisible(true);
                        }
                    } else {
                        lbl_error_DescripcionProducto.setVisible(true);
                    }
                } else {
                    lbl_error_NombreProducto.setVisible(true);
                }
            } else {
                lbl_error_IDproducto.setVisible(true);

            }
        } else {
            JOptionPane.showMessageDialog(null, "No tiene los permisos suficientes");
            LimpiarCampos();
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        GestionProducto CLI = new GestionProducto();

        Gestion_Administrativos GAdmin = new Gestion_Administrativos();
        cls_administrativos OBJAdmin = new cls_administrativos();

        usuario = OBJAdmin.getUsuario1();
        con = OBJAdmin.getContrasena();
        cls_administrativos tipo_nivel = GAdmin.GuardarDatos(usuario, con);

        System.out.println(tipo_nivel);
        if (tipo_nivel.getTipo_usuario().equals("Administrador")) {
            Errores();
            String ID;
            String Nombre;
            String Descripcion;
            String Cantidad;
            String Categoria;
            String Precio_deC;
            String Precio_deV;

            ID = txt_id_producto.getText();
            Nombre = txt_nombre_producto.getText();
            Descripcion = txt_descripcion_producto.getText();
            Cantidad = sp_cantidad_prodcuto.getValue().toString();
            Categoria = cbx_categoria_producto.getSelectedItem().toString();
            Precio_deC = txt_precio_de_compra.getText();
            Precio_deV = txt_precio_de_venta.getText();
            if (!ID.equalsIgnoreCase("")) {
                if (!Nombre.equalsIgnoreCase("")) {
                    if (!Descripcion.equalsIgnoreCase("")) {
                        if (!Cantidad.equalsIgnoreCase("0")) {
                            if (!Categoria.equalsIgnoreCase("Seleccione el item")) {
                                if (!Precio_deC.equalsIgnoreCase("")) {
                                    if (!Precio_deV.equalsIgnoreCase("")) {

                                        //ACCIONES
                                        Objects.clsProductos objProductos = new Objects.clsProductos();
                                        objProductos.setIDProd(Integer.parseInt(ID));
                                        objProductos.setNombreProd(Nombre);
                                        objProductos.setDescripProd(Descripcion);
                                        objProductos.setCantidadProd(Integer.parseInt(Cantidad));
                                        objProductos.setCategoriaProd(Categoria);
                                        objProductos.setPrecioCompra(Double.parseDouble(Precio_deC));
                                        objProductos.setPrecioVenta(Double.parseDouble(Precio_deV));

                                        JOptionPane.showMessageDialog(null, CLI.ActualizarProducto(objProductos, Long.parseLong(ID)));
                                        LimpiarCampos();
                                        LlenarTabla();
                                    } else {
                                        lbl_error_preciodeventa.setVisible(true);
                                    }
                                } else {
                                    lbl_error_preciodecompra.setVisible(true);
                                }
                            } else {
                                lbl_error_categoria.setVisible(true);

                            }
                        } else {
                            lbl_error_cantidad.setVisible(true);
                        }
                    } else {
                        lbl_error_DescripcionProducto.setVisible(true);
                    }
                } else {
                    lbl_error_NombreProducto.setVisible(true);
                }
            } else {
                lbl_error_IDproducto.setVisible(true);

            }
        } else {
            JOptionPane.showMessageDialog(null, "No tiene los permisos suficientes");
            LimpiarCampos();
        }
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        String IDCli = txt_id_producto.getText();
        GestionProducto GCliente = new GestionProducto();
        clsProductos objProducto = new clsProductos();

        if (!IDCli.equalsIgnoreCase(null)) {
            int idcliente = Integer.parseInt(IDCli);
            objProducto = GCliente.BuscarPorID(idcliente);

            txt_id_producto.setText(String.valueOf(objProducto.getIDProd()));
            txt_nombre_producto.setText(objProducto.getNombreProd());
            txt_descripcion_producto.setText(objProducto.getDescripProd());
            sp_cantidad_prodcuto.setValue(objProducto.getCantidadProd());
            cbx_categoria_producto.setSelectedItem(objProducto.getCategoriaProd());
            txt_precio_de_compra.setText(String.valueOf(objProducto.getPrecioCompra()));
            txt_precio_de_venta.setText(String.valueOf(objProducto.getPrecioVenta()));

            JOptionPane.showMessageDialog(null, "Cliente encontrado exitosamente");

        } else {
            lbl_error_IDproducto.setVisible(true);
        }
    }//GEN-LAST:event_btn_mostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PN_data;
    private javax.swing.JPanel PN_main;
    private javax.swing.JPanel PN_table;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JComboBox<String> cbx_categoria_producto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_$_precio_compra;
    private javax.swing.JLabel lbl_$_precio_venta;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_descri1;
    private javax.swing.JLabel lbl_descri2;
    private javax.swing.JLabel lbl_error_DescripcionProducto;
    private javax.swing.JLabel lbl_error_IDproducto;
    private javax.swing.JLabel lbl_error_NombreProducto;
    private javax.swing.JLabel lbl_error_cantidad;
    private javax.swing.JLabel lbl_error_categoria;
    private javax.swing.JLabel lbl_error_preciodecompra;
    private javax.swing.JLabel lbl_error_preciodeventa;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_precio_compra;
    private javax.swing.JLabel lbl_precio_venta;
    private javax.swing.JSpinner sp_cantidad_prodcuto;
    private javax.swing.JTable tbl_pro;
    private javax.swing.JTextField txt_descripcion_producto;
    private javax.swing.JTextField txt_id_producto;
    private javax.swing.JTextField txt_nombre_producto;
    private javax.swing.JTextField txt_precio_de_compra;
    private javax.swing.JTextField txt_precio_de_venta;
    // End of variables declaration//GEN-END:variables
}
