/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Gestion_Administrativos;
import Conexion.conexion_bd;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDarkerIJTheme;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author juanse
 */
public class frm_register extends javax.swing.JFrame {

    int xMouse, yMouse;
    conexion_bd Conn;

    public frm_register() {
        initComponents();
        this.setLocationRelativeTo(this);
        Conn = new conexion_bd();
        Conn.establecer();
        Errores();
        LimpiarCampos();
    }

    public void Errores() {
        lbl_error_nombre.setVisible(false);
        lbl_Error_apellido.setVisible(false);
        lbl_Error_contrasena.setVisible(false);
        lbl_error_tipo_usuario.setVisible(false);
        lbl_errorr_usuario.setVisible(false);
    }

    public void LimpiarCampos() {
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_usuario.setText("");
        cbx_tipo_usuario.setSelectedItem(0);
        txt_contrasena.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        txt_contrasena = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        cbx_tipo_usuario = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        PN_registrar = new javax.swing.JPanel();
        lbl_registrar = new javax.swing.JLabel();
        PN_salir = new javax.swing.JPanel();
        lbl_salir = new javax.swing.JLabel();
        PN_navbar = new javax.swing.JPanel();
        PN_exit = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        lbl_Error_contrasena = new javax.swing.JLabel();
        lbl_error_nombre = new javax.swing.JLabel();
        lbl_Error_apellido = new javax.swing.JLabel();
        lbl_errorr_usuario = new javax.swing.JLabel();
        lbl_error_tipo_usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 400));
        setUndecorated(true);
        setResizable(false);

        main.setBackground(new java.awt.Color(0, 0, 0));
        main.setMinimumSize(new java.awt.Dimension(510, 400));
        main.setPreferredSize(new java.awt.Dimension(510, 400));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_contrasena.setBackground(new java.awt.Color(0, 0, 0));
        txt_contrasena.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        txt_contrasena.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "CONTRASEÑA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        txt_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contrasenaActionPerformed(evt);
            }
        });
        main.add(txt_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 230, 50));

        txt_nombre.setBackground(new java.awt.Color(0, 0, 0));
        txt_nombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "NOMBRE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        main.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 230, 50));

        txt_apellido.setBackground(new java.awt.Color(0, 0, 0));
        txt_apellido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "APELLIDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        main.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 230, 50));

        txt_usuario.setBackground(new java.awt.Color(0, 0, 0));
        txt_usuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        main.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, 50));

        cbx_tipo_usuario.setBackground(new java.awt.Color(0, 0, 0));
        cbx_tipo_usuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbx_tipo_usuario.setForeground(new java.awt.Color(255, 255, 255));
        cbx_tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Administrador", "Trabajador" }));
        cbx_tipo_usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "TIPO DE USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 15))); // NOI18N
        cbx_tipo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tipo_usuarioActionPerformed(evt);
            }
        });
        main.add(cbx_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 230, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PN_registrar.setBackground(new java.awt.Color(0, 0, 0));
        PN_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PN_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PN_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PN_registrarMouseExited(evt);
            }
        });
        PN_registrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_registrar.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        lbl_registrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_registrar.setText("REGISTRAR");
        lbl_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_registrarMouseClicked(evt);
            }
        });
        PN_registrar.add(lbl_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 60));

        jPanel1.add(PN_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 60));

        PN_salir.setBackground(new java.awt.Color(0, 0, 0));
        PN_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PN_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PN_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PN_salirMouseExited(evt);
            }
        });
        PN_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_salir.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        lbl_salir.setForeground(new java.awt.Color(255, 255, 255));
        lbl_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_salir.setText("SALIR");
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
        });
        PN_salir.add(lbl_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 60));

        jPanel1.add(PN_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 60));

        main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 220, 240));

        PN_navbar.setBackground(new java.awt.Color(0, 0, 0));
        PN_navbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PN_navbarMouseDragged(evt);
            }
        });
        PN_navbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PN_navbarMousePressed(evt);
            }
        });
        PN_navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PN_exit.setBackground(new java.awt.Color(0, 0, 0));
        PN_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PN_exitMouseClicked(evt);
            }
        });
        PN_exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_exit.setBackground(new java.awt.Color(0, 0, 0));
        lbl_exit.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
        });
        PN_exit.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        PN_navbar.add(PN_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 30));

        main.add(PN_navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 30));

        lbl_Error_contrasena.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lbl_Error_contrasena.setForeground(new java.awt.Color(187, 0, 0));
        lbl_Error_contrasena.setText("Error*llene el campo de tipo de contraseña");
        main.add(lbl_Error_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 20));

        lbl_error_nombre.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lbl_error_nombre.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_nombre.setText("Error*llene el campo de nombre");
        main.add(lbl_error_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        lbl_Error_apellido.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lbl_Error_apellido.setForeground(new java.awt.Color(187, 0, 0));
        lbl_Error_apellido.setText("Error*llene el campo de apellido");
        main.add(lbl_Error_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        lbl_errorr_usuario.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lbl_errorr_usuario.setForeground(new java.awt.Color(187, 0, 0));
        lbl_errorr_usuario.setText("Error*llene el campo de usuario");
        main.add(lbl_errorr_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        lbl_error_tipo_usuario.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lbl_error_tipo_usuario.setForeground(new java.awt.Color(187, 0, 0));
        lbl_error_tipo_usuario.setText("Error*llene el campo de tipo de usuario");
        main.add(lbl_error_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contrasenaActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void PN_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_registrarMouseEntered
        PN_registrar.setBackground(Color.WHITE);
        lbl_registrar.setForeground(Color.BLACK);
    }//GEN-LAST:event_PN_registrarMouseEntered

    private void PN_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_registrarMouseExited
        PN_registrar.setBackground(Color.BLACK);
        lbl_registrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_PN_registrarMouseExited

    private void PN_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_salirMouseEntered
        PN_salir.setBackground(Color.WHITE);
        lbl_salir.setForeground(Color.BLACK);
    }//GEN-LAST:event_PN_salirMouseEntered

    private void PN_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_salirMouseExited
        PN_salir.setBackground(Color.BLACK);
        lbl_salir.setForeground(Color.WHITE);

    }//GEN-LAST:event_PN_salirMouseExited

    private void PN_navbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_navbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_PN_navbarMousePressed

    private void PN_navbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_navbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_PN_navbarMouseDragged

    private void PN_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_exitMouseClicked

    }//GEN-LAST:event_PN_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        PN_exit.setBackground(Color.WHITE);
        lbl_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        PN_exit.setBackground(Color.BLACK);
        lbl_exit.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbl_exitMouseExited

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        frm_register frm = new frm_register();
        frm.setVisible(false);
        frmLogin frmLog = new frmLogin();
        frmLog.setVisible(true);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        frm_register frm = new frm_register();
        frm.setVisible(false);
        frmLogin frmLog = new frmLogin();
        frmLog.setVisible(true);
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void lbl_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registrarMouseClicked
        Gestion_Administrativos GAdmin = new Gestion_Administrativos();
        Errores();
        
        String Nombre = txt_nombre.getText();
        String Apellido = txt_apellido.getText();
        String Contrasena = txt_contrasena.getText();
        String tipoUsuario = cbx_tipo_usuario.getSelectedItem().toString();
        String Usuario = txt_usuario.getText();

        if (!Nombre.equalsIgnoreCase("")) {
            if (!Apellido.equalsIgnoreCase("")) {
                if (!Usuario.equalsIgnoreCase("")) {
                    if (!tipoUsuario.equalsIgnoreCase("Selecciona")) {
                        if (!Contrasena.equalsIgnoreCase("")) {
                            Objects.cls_administrativos OBJAdmin = new Objects.cls_administrativos();
                            OBJAdmin.setNombres(Nombre);
                            OBJAdmin.setApellidos(Apellido);
                            OBJAdmin.setUsuario(Usuario);
                            OBJAdmin.setTipo_usuario(tipoUsuario);
                            OBJAdmin.setContraseña(Contrasena);
                             
                            
                            JOptionPane.showMessageDialog(null,GAdmin.Crear_Cliente(OBJAdmin));
                            LimpiarCampos();

                        } else {
                            lbl_Error_contrasena.setVisible(true);
                        }
                    } else {
                        lbl_error_tipo_usuario.setVisible(true);
                    }
                } else {
                    lbl_errorr_usuario.setVisible(true);
                }

            } else {
                lbl_Error_apellido.setVisible(true);
            }
        } else {
            lbl_error_nombre.setVisible(true);
        }
    }//GEN-LAST:event_lbl_registrarMouseClicked

    private void cbx_tipo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tipo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tipo_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialDarkerIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PN_exit;
    private javax.swing.JPanel PN_navbar;
    private javax.swing.JPanel PN_registrar;
    private javax.swing.JPanel PN_salir;
    private javax.swing.JComboBox<String> cbx_tipo_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Error_apellido;
    private javax.swing.JLabel lbl_Error_contrasena;
    private javax.swing.JLabel lbl_error_nombre;
    private javax.swing.JLabel lbl_error_tipo_usuario;
    private javax.swing.JLabel lbl_errorr_usuario;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_registrar;
    private javax.swing.JLabel lbl_salir;
    private javax.swing.JPanel main;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_contrasena;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
